### ISSUE TITLE
DEV-1 Setup Development Stack

### ISSUE THREAD

**Issue by kwalter26** [Titanburg/band-uniform#1]
use Node with PostgreSQL to build an application based on the internet. Use angular and android studio for the user interfaces.

Priority: M
Estimate: 2h
Category: NF

Acceptance Criterion: 
1. Create package.
2. Configure MongoDB
3. ReadMe for installation.

**Comment by kwalter26** [comment]
Reopened to add angular

**Comment by Dreamwalker420** [comment]
Edited to change to MongoDB
