### ISSUE TITLE
ADMIN-11 Administrator Request Control

### ISSUE THREAD

**Issue by kwalter26** [Titanburg/band-uniform#103]

**Comment by kwalter26** [comment]
Added dynamic filtering buttons.
Added state parameter to user schema.
Added state to user table.
Added state dropdown in user editor.
Added state to login control. If user is pending or disabled they cannot enter. 
Added deletion confirmation.
Added validation for state dropdown.

**Comment by kwalter26** [comment]
Also added first name and last name to user account request form.

**Comment by Dreamwalker420** [comment]
Not forgotten, just a little busy

Kirk Powell
kirk@thegamestoreapp.com

"_Crave rejection, love disappointment and be fearless in your failures;
for that is the path to success._"
