### ISSUE TITLE
DEV-4 Database

### ISSUE THREAD

**Issue by kjarrett316** [Titanburg/band-uniform#17]
Story: As a developer, I want access to a database of uniforms to manipulate. 

Category: Nonfunctional
Priority: M
Estimate: 8hrs
Left: 4hrs

Acceptance Criterion: 
1. Table for available uniforms.
2. Table for member/uniform pairing
3. Table of band members.
4. Model for uniforms.
5. Use prepared statements.

**Comment by kwalter26** [comment]
Added mongoose to application for accessing mongoDB database. Also, created models for jackets, jumpsuits, hats, and users. Also commented app.js and the passport library.

2hrs

**Comment by kwalter26** [comment]
Updated all the models and created seeding file for jackets,jumpsuits,and hats. The hats are just dumby data right now but jackets and jumpsuits are right from the list.

2hr

**Comment by kjarrett316** [comment]
Reviewed the database.
