### ISSUE TITLE
USER-11 User Interface

### ISSUE THREAD

**Issue by kjarrett316** [Titanburg/band-uniform#4]
As a user, I want the web application to have intuitive user interface for my ease of use.

Priority: M
Estimate: 4hrs

Acceptance Criterion: 
1. Should render correctly.
2. Gives failure message if page cannot load.

**Comment by Dreamwalker420** [comment]
I know about Kyle's love affair with Jade.  So I will implement Jade for this project too.

**Comment by Dreamwalker420** [comment]
Add MVC tasks to Sprint 1.0

**Comment by Dreamwalker420** [comment]
The first part of this is on track.  This story should be reviewed again in the future to ensure that the design elements are sufficient.

**Comment by Dreamwalker420** [comment]
Added to the Project Requirements (this card went missing).

**Comment by Dreamwalker420** [comment]
This is in  Code Review.
