### ISSUE TITLE
Accounts

### ISSUE THREAD

**Issue by kwalter26** [Titanburg/band-uniform#5]
As a developer, I need user and admin level accounts to determine level of access.

Priority: M
Estimate: 4hr
Left: 2hr

Acceptance Criterion: 
1. Account should have username/password.
2. Model for user accounts.

**Comment by Dreamwalker420** [comment]
Can we use single sign-on access with Passport for this?

**Comment by kwalter26** [comment]
I think so. It will definitely work on web but we will have to figure out the best way to do it with android.

**Comment by kwalter26** [comment]
Added passport and routes for signup and login. 
Double checked user model. I used email as the username field. 

1hr

**Comment by kwalter26** [comment]
Basic login and signup working. I am going to add the rest of the user account attributes like their sizes under the web api issue.

1hr

**Comment by Dreamwalker420** [comment]
I noticed we don't have a logout on the user accounts.  But it worked correctly!
