### ISSUE TITLE
Build Express User Controller

### ISSUE THREAD

**Issue by kwalter26** [Titanburg/band-uniform#50]

**Comment by kwalter26** [comment]
Added controller file.
Added skeleton for all methods needed. 
Only wrote content of the getUsers method.

**Comment by kwalter26** [comment]
Ready for code review

**Comment by kjarrett316** [comment]
Found errors on lines 36 and 77.

**Comment by kwalter26** [comment]
This error is due to validation not being present. The sprint 2 story for this is #55 .
