### ISSUE TITLE
Add an error message when attempting to access invalid portion of website.

### ISSUE THREAD

**Issue by Dreamwalker420** [Titanburg/band-uniform#82]
This is a task for Issue #4

**Comment by Dreamwalker420** [comment]
Invalid is anything that a route does not exist for or an attempt to access a page not authorized

**Comment by Dreamwalker420** [comment]
404 and 500 pages already exist.  However, everything is routed to the auth/login if it is invalid

**Comment by kwalter26** [comment]
Looks good. The functionality is exactly what we need but we might want to explore a better way to code it. We talked about a story for this but we just need to create it.

**Comment by Dreamwalker420** [comment]
I removed the Q&A tag since we are not doing that on Band Uniform.  Added a story to address Kyle's note about what a better way may be.
