### ISSUE TITLE
Update controller for editing user

### ISSUE THREAD

**Issue by kwalter26** [Titanburg/band-uniform#94]
The post function is not accounting for blank fields being submitted. Although this will change in some instances with client side validation there may still be some blank fields submitted.

**Comment by kwalter26** [comment]
Fixed all undefined key errors by checking first to see if parent key is present before testing child key.  For instance testing user.local before testing user.local.email. There is not other validation in this branch.

**Comment by kjarrett316** [comment]
Looks good to me. No crashing.
